wisdom = [
    "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.",
    "Happiness is a warm puppy",
    "Dogs never bite me. Just humans.",
    "If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.",
    "Owners of dogs will have noticed that, if you provide them with food and water and shelter and affection, they will think you are god. Whereas owners of cats are compelled to realize that, if you provide them with food and water and shelter and affection, they draw the conclusion that they are gods.",
    "Dogs are our link to paradise. They don't know evil or jealousy or discontent. To sit with a dog on a hillside on a glorious afternoon is to be back in Eden, where doing nothing was not boring--it was peace",
    "Meow” means “woof” in cat.",
    "If there are no dogs in Heaven, then when I die I want to go where they went",
    "A dog is the only thing on earth that loves you more than he loves himself.",
    "Dog's lives are too short. Their only fault, really.",
    "A dog is the only thing that can mend a crack in your broken heart.",
    "The average dog is a nicer person than the average person.",
    "The dog is a gentleman; I hope to go to his heaven not man's.",
    "Be the person your dog thinks you are.",
    "If a man aspires towards a righteous life, his first act of abstinence is from injury to animals.",
    "If I could be half the person my dog is, I'd be twice the human I am.",
    "Dogs leave pawprints on our hearts.",
    "No one appreciates the very special genius of your conversation as a dog does.",
    "Does not the gratitude of the dog put to shame any man who is ungrateful to his benefactors?",
    "Even the tiniest Poodle or Chihuahua is still a wolf at heart.",
    "The old saw about old dogs and new tricks only applies to certain people.",
    "Outside of a dog, a book is a man's best friend. Inside of a dog it's too dark to read.",
    "Before you get a dog, you can’t quite imagine what living with one might be like; afterward, you can’t imagine living any other way.",
    "No animal I know of can consistently be more of a friend and companion than a dog.",
    "Once you have had a wonderful dog, a life without one is a life diminished.",
    "The dog was created specially for children. He is the god of frolic.",
    "Home is where the dog runs to greet you.",
    "You think dogs will not be in heaven? I tell you; they will be there long before any of us.",
    "A dog can snap you out of any kind of bad mood that you're in faster than you can think of.",
    "The bond with a true dog is as lasting as the ties of this earth will ever be.",
    "People love dogs. You can never go wrong adding a dog to the story.",
    "It is amazing how much love and laughter they bring into our lives and even how much closer we become with each other because of them.",
    "Why does watching a dog be a dog fill one with happiness?",
    "A dog is the only thing on earth that loves you more than he loves himself.",
    "Money can buy you a fine dog, but only love can make him wag his tail."
]
